// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class GemPricer
{
    /// <summary>
    /// model input class for GemPricer.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"H1")]
        public float H1 { get; set; }

        [ColumnName(@"carat")]
        public float Carat { get; set; }

        [ColumnName(@"cut")]
        public string Cut { get; set; }

        [ColumnName(@"color")]
        public float Color { get; set; }

        [ColumnName(@"clarity")]
        public float Clarity { get; set; }

        [ColumnName(@"depth")]
        public float Depth { get; set; }

        [ColumnName(@"table")]
        public float Table { get; set; }

        [ColumnName(@"x")]
        public float X { get; set; }

        [ColumnName(@"y")]
        public float Y { get; set; }

        [ColumnName(@"z")]
        public float Z { get; set; }

        [ColumnName(@"price")]
        public float Price { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for GemPricer.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"H1")]
        public float H1 { get; set; }

        [ColumnName(@"carat")]
        public float Carat { get; set; }

        [ColumnName(@"cut")]
        public float[] Cut { get; set; }

        [ColumnName(@"color")]
        public float Color { get; set; }

        [ColumnName(@"clarity")]
        public float Clarity { get; set; }

        [ColumnName(@"depth")]
        public float Depth { get; set; }

        [ColumnName(@"table")]
        public float Table { get; set; }

        [ColumnName(@"x")]
        public float X { get; set; }

        [ColumnName(@"y")]
        public float Y { get; set; }

        [ColumnName(@"z")]
        public float Z { get; set; }

        [ColumnName(@"price")]
        public float Price { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("../GemPricer_gen1/GemPricer.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
